version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 3
    command: ["--max_allowed_packet=1G"]

  stock-manager-server:
    image: stockamanager/stock-manager-server:latest
    container_name: stock-manager-server
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - mynet
    depends_on:
      mysql:
        condition: service_healthy
  

  stock-manager-client:
     image: stockamanager/stock-manager-client:latest
     container_name: stock-manager-client
     environment:
       REACT_APP_ENV: production
     ports:
       - "3000:3000"
     networks:
       - mynet
     depends_on:
       - stock-manager-server

