version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 3
    command: ["--max_allowed_packet=1G"]

  gdfuture-server:
    image: gdfuture/gdfuture-server:27.02.2025.19.48.54
    container_name: gdfuture-server
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - mynet
    depends_on:
      mysql:
        condition: service_healthy
  

  gdfuture-client:
     image: gdfuture/gdfuture-client:03.03.2025.13.45.18
     container_name: gdfuture-client
     environment:
       REACT_APP_ENV: production
     ports:
       - "3000:3000"
     networks:
       - mynet
     depends_on:
       - gdfuture-server

  gdfuture-management:
     image: gdfuture/gdfuture-management:03.03.2025.19.40.59
     container_name: gdfuture-management
     environment:
       REACT_APP_ENV: production
     ports:
       - "3001:3001"
     networks:
       - mynet
     depends_on:
       - gdfuture-server
